// Team data with realistic roles
  const teamMembers: TeamMember[] = [
    // Committee Heads
    {
      id: 1,
      name: "Mann Shah",
      role: "Committee Head",
      category: "Core",
      description: "Chief of Breaking Things and Fixing Them at 2 AM",
      photo: "/mann.jpg",
      github: "https://github.com/mannn13",
      linkedin: "https://www.linkedin.com/in/mann-shah-3940a3278/",
      instagram: "https://www.instagram.com/m.annn13/",
    },
    {
      id: 2,
      name: "Siddharth Chintawar",
      role: "Committee Head",
      category: "Core",
      photo: "/siddarth.jpg",
      description: "Steering the ship, barely",
      github: "https://github.com/sidc124",
      linkedin: "https://www.linkedin.com/in/siddharth-chintawar-a76366291/",
      instagram: "https://www.instagram.com/godknowssid/",
    },
    // Tech Head and Members
    {
      id: 3,
      name: "Shubham Indulkar",
      role: "Tech Head",
      category: "Technical",
      description: "Name's PyKnight73",
      photo: "/shubham.png",
      github: "https://github.com/shubham-indulkar",
      linkedin: "https://www.linkedin.com/in/shubham-indulkar",
      instagram: "https://www.instagram.com/shubham.indulkar",
    },
    {
      id: 4,
      name: "Ishika Bhoyar",
      role: "Tech Member",
      category: "Technical",
      description: "It is what it is",
      photo: "/ishika.png",
      github: "https://github.com/ishikabhoyar",
      linkedin: "https://www.linkedin.com/in/ishikabhoyar",
      instagram: "https://www.instagram.com/ishika.bhoyar/",
    },
    {
      id: 5,
      name: "Soham Gore",
      role: "Tech Member",
      category: "Technical",
      description: "I am always... plotting .",
      photo: "/soham.jpg",
      github: "https://github.com/SohamGore",
      linkedin: "https://www.linkedin.com/in/soham-gore/",
      instagram: "https://www.instagram.com/sohamgore/",
    },
    {
      id: 6,
      name: "Manas Kolaskar",
      role: "Tech Member",
      category: "Technical",
      description: "Designing user-friendly and engaging experiences.",
      photo: "/manas.jpg",
      github: "https://github.com/manaskolaskar",
      linkedin: "https://www.linkedin.com/in/manas-kolaskar/",
      instagram: "https://www.instagram.com/manas.kolaskar/",
    },
    {
      id: 7,
      name: "Lakshya",
      role: "Tech Member",
      category: "Technical",
      description: "Introverted for a reason",
      photo: "/lakshya.png",
      github: "https://github.com/lakshya",
      linkedin: "https://www.linkedin.com/in/lakshya/",
      instagram: "https://www.instagram.com/lakshya/",
    },
    // Creative Head and Members
    {
      id: 8,
      name: "Swadha Kumari",
      role: "Creative Head",
      category: "Content",
      description: "Certified Yapper",
      photo: "/swadha.jpg",
      github: "https://github.com/Swadha06",
      linkedin: "https://www.linkedin.com/in/swadha-kumari-525a61294/",
      instagram: "https://www.instagram.com/swaddhaa._/",
    },
    {
      id: 9,
      name: "Riya Gupta",
      role: "Creative Member",
      category: "Content",
      description: "Designing visual experiences",
      photo: "/riyagupta.jpg",
      github: "https://github.com/riyaa-g",
      linkedin: "https://www.linkedin.com/in/riyagupta70/",
      instagram: "https://www.instagram.com/_riyaya_07/",
    },
    {
      id: 10,
      name: "Sachi Parekh",
      role: "Creative Member",
      category: "Content",
      description: "Dedicated - Diligent - Devoted",
      photo: "/sachi.jpg",
      github: "https://github.com/sachiparekh",
      linkedin: "https://linkedin.com/in/sachi-parekh",
      instagram: "https://www.instagram.com/sachi.parekh",
    },
    {
      id: 11,
      name: "Samiksha Phirangi",
      role: "Creative Member",
      category: "Content",
      description: "Creating and planning content strategies.",
      photo: "/samiksha.jpg",
      github: "https://github.com/samikshaphirangi",
      linkedin: "https://www.linkedin.com/in/samiksha-phirangi",
      instagram: "https://www.instagram.com/samiksha.phirangi/",
    },
    {
      id: 12,
      name: "Saanj Patil",
      role: "Creative Member",
      category: "Content",
      description: "Ensuring the safety and security of systems.",
      photo: "/saanj.jpg",
      github: "https://github.com/saanjpatil",
      linkedin: "https://www.linkedin.com/in/saanj-patil/",
      instagram: "https://www.instagram.com/saanj.patil/",
    },
    // PR Head and Members
    {
      id: 13,
      name: "Sohom Mallick",
      role: "PR Head",
      category: "Outreach",
      description: "Making tech look good",
      photo: "/sohom.jpg",
      github: "https://github.com/sohommallick",
      linkedin: "https://www.linkedin.com/in/sohom-mallick/",
      instagram: "https://www.instagram.com/sohom.mallick/",
    },
    {
      id: 14,
      name: "Pratibha Singh",
      role: "PR Member",
      category: "Outreach",
      description: "Designing seamless digital experiences.",
      photo: "/pratibha.PNG",
      github: "https://github.com/pratibhasoup",
      linkedin: "https://www.linkedin.com/in/pratibha-singh-76bb51340/",
      instagram: "https://www.instagram.com/pratibha.singhh/",
    },
    {
      id: 15,
      name: "Mrinali Sharma",
      role: "PR Member",
      category: "Outreach",
      description: "50%sweetness 50%savage",
      photo: "/mrinali.jpg",
      github: "https://github.com/mrinalishh",
      linkedin: "https://www.linkedin.com/in/mrinali-sharma-353b92327/",
      instagram: "https://www.instagram.com/mrinaliisharma?igsh=MTRocWI5a2s2eDI0bA==",
    },
    {
      id: 16,
      name: "Gurkirat Kaur",
      role: "PR Member",
      category: "Outreach",
      description: "Cosmic Wanderer",
      photo: "/gurkirat.jpg",
      github: "https://github.com/GurkiratKaur22",
      linkedin: "https://www.linkedin.com/in/gurkirat-kaur-b159a12b4/",
      instagram: "https://www.instagram.com/gurkirat_227/profilecard/?igsh=MXdoNDE5ZDhpYzc5cQ%3D%3D",
    },
    {
      id: 17,
      name: "Manya Baranwal",
      role: "PR Member",
      category: "Outreach",
      description: "Creating connections",
      photo: "/manya.jpg",
      github: "https://github.com/manyabaranwal",
      linkedin: "https://www.linkedin.com/in/manya-baranwal/",
      instagram: "https://www.instagram.com/manya.baranwal/",
    },
    // Marketing Head and Members
    {
      id: 18,
      name: "Abdullah Qureshi",
      role: "Marketing Head",
      category: "Marketing",
      description: "Strategic marketing expert",
      photo: "/abdullah.jpg",
      github: "https://github.com/abdullahqureshi",
      linkedin: "https://www.linkedin.com/in/abdullah-qureshi/",
      instagram: "https://www.instagram.com/abdullah.qureshi/",
    },
    {
      id: 19,
      name: "Ankita Kotkar",
      role: "Marketing Member",
      category: "Marketing",
      description: "Keepin' it real",
      photo: "/ankita.jpg",
      github: "https://github.com/ankitakotkar",
      linkedin: "https://www.linkedin.com/in/ankita-kotkar/",
      instagram: "https://www.instagram.com/ankita.kotkar/",
    },
    {
      id: 20,
      name: "Suryaansh Jain",
      role: "Marketing Member",
      category: "Marketing",
      description: "Doin it for the plot",
      photo: "/suryaansh.jpg",
      github: "https://github.com/suryaansh-jain",
      linkedin: "https://in.linkedin.com/in/suryaansh-jain-61b74b28a",
      instagram: "https://www.instagram.com/suryaansh._._/profilecard/?igsh=cmw0OXh4ZHY4Nzlm",
    },
    {
      id: 21,
      name: "Maahnal Chauhan",
      role: "Marketing Member",
      category: "Marketing",
      description: "Turning ideas into campaigns",
      photo: "/maahnal.jpg",
      github: "https://github.com/maahnalchauhan",
      linkedin: "https://www.linkedin.com/in/maahnal-chauhan/",
      instagram: "https://www.instagram.com/maahnal.chauhan/",
    },
    // Operations Head and Members
    {
      id: 22,
      name: "Vedant Padhy",
      role: "Operation Head",
      category: "Operations",
      description: "Efficiency expert",
      photo: "/vedant.png",
      github: "https://github.com/vedantpadhy",
      linkedin: "https://www.linkedin.com/in/vedant-padhy/",
      instagram: "https://www.instagram.com/vedant.padhy/",
    },
    {
      id: 23,
      name: "Abhishek Joshi",
      role: "Operation Member",
      category: "Operations",
      description: "Fueled by Coffee & Code",
      photo: "/abhishek.png",
      github: "https://github.com/ketanabhishek8",
      linkedin: "https://www.linkedin.com/in/abhishek-joshi-83b482340/",
      instagram: "https://www.instagram.com/ketanabhishek8/profilecard/?igsh=Mzhjc2swMjdmOXc4",
    },
    {
      id: 24,
      name: "Naman Lodha",
      role: "Operation Member",
      category: "Operations",
      description: "good mornin",
      photo: "/naman.png",
      github: "https://github.com/namanldoha",
      linkedin: "https://www.linkedin.com/in/lodhanaman",
      instagram: "https://www.instagram.com/naman.ld",
    },
    {
      id: 25,
      name: "Rayan J Castelino",
      role: "Operation Member",
      category: "Operations",
      description: "Process optimization specialist",
      photo: "/rayan.jpg",
      github: "https://github.com/rayanjcastelino",
      linkedin: "https://www.linkedin.com/in/rayan-castelino/",
      instagram: "https://www.instagram.com/rayan.castelino/",
    },
    {
      id: 26,
      name: "Ishwari Chopade",
      role: "Operation Member",
      category: "Operations",
      description: "Efficiency advocate",
      photo: "/ishwari.jpg",
      github: "https://github.com/ishwarichopade",
      linkedin: "https://www.linkedin.com/in/ishwari-chopade/",
      instagram: "https://www.instagram.com/ishwari.chopade/",
    }
  ];
